const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCES: 'FETCH_COLLECTIONS_SUCCES',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'
};

export default ShopActionTypes;
